### ISSUE TITLE
Urls don't provide name of paper

### ISSUE THREAD

**Issue by jacksongoode** [jacksongoode/NIME-proceedings-analyzer#2]
PubPub urls are seemingly random or author assigned. Thus the files created will be a random string. The year and article number will need to be used to name these files.

It also might make sense to do this for _all_ files so as not to rely upon urls for saved file names.

**Comment by stefanofasciani** [comment]
From 2021 onward, the bibtex entries include also the field "article-number", which can be used to generate a unique name for the downloaded pdf files (aligned with naming for pre "PubPub" editions).

**Comment by stefanofasciani** [comment]
The NIME bibtex file has been moved to another location and "article-number" renamed to "articleno". This is commits 0cbc4c8af38634984fd24fe0f789a7c515d7eb65 and ad17b6ab879be2b4e9ff245b3d33bb71abc0e2a9 .
