### ISSUE TITLE
Adjust stats generation for PubPub

### ISSUE THREAD

**Issue by jacksongoode** [jacksongoode/NIME-proceedings-analyzer#3]
One obvious missing stat will be pages, but there my be other adjustments we may need to make. I think it makes sense in the case of pages to put as 'N/A' as well as others that may not be applicable.

**Comment by stefanofasciani** [comment]
When considering together "pre" and "post" PubPub papers, the word count (of the body text) is the best metric to analyze the length of the paper. For the page length, it make sense to present separately the stats "pre" and "post" PubPub.

**Comment by stefanofasciani** [comment]
solved with https://github.com/jacksongoode/NIME-proceedings-analyzer/commit/27bb411f05b49535743493981e5eabea54623aea
